'use strict';
const STORE='yyc_site_v4';
const ADMIN={lxshhadmin:'yyclxshhboss'};
const DEFAULTS={
 leaders:[{id:'leader-1',name:'AHWIN Y',role:'PRESIDENT',line:'YUVAKESARI YOUTH CLUB · SUBRAHMANYA',photo:'',scale:1,posX:50,posY:50}],
 members:[],updates:[{id:'update-1',title:'Welcome to Yuvakesari Youth Club',body:'Youth energy, community spirit and meaningful action — together from Subrahmanya.',date:new Date().toISOString().slice(0,10)}],
 gallery:[{id:'gallery-1',title:'Dharma Daiva · Tulunadu',src:'assets/dharma-daiva.webp'},{id:'gallery-2',title:'Aati Kalenja · Tulunadu',src:'assets/aati-kalenja.webp'},{id:'gallery-3',title:'Yakshagana · Coastal Art',src:'assets/yakshagana.webp'}],
 pendingMembers:[],pendingUpdates:[],pendingGallery:[],
 socials:{instagram:'https://www.instagram.com/yuvakesari__kukke/',whatsapp:'https://chat.whatsapp.com/FW4v1bvUKYW4DDgTcKTYFL?s=sw&p=a&mlu=4&ilr=4',x:'',facebook:''},
 settings:{clubName:'YUVAKESARI YOUTH CLUB',location:'SUBRAHMANYA · KARNATAKA',slogan:'ಧರ್ಮೋ ರಕ್ಷಿತ ರಕ್ಷಿತಃ🚩'}
};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const deep=o=>JSON.parse(JSON.stringify(o));
function load(){try{const d=JSON.parse(localStorage.getItem(STORE));return mergeDefaults(d)}catch{ return deep(DEFAULTS)}}
function mergeDefaults(d){const out=deep(DEFAULTS);if(!d||typeof d!=='object')return out;for(const k of Object.keys(out)){if(Array.isArray(out[k]))out[k]=Array.isArray(d[k])?d[k]:out[k];else if(out[k]&&typeof out[k]==='object')out[k]=Object.assign(out[k],d[k]||{});else if(d[k]!=null)out[k]=d[k]}return out}
let db=load(), modalOpen=false,currentAdmin=null;
function save(){localStorage.setItem(STORE,JSON.stringify(db));renderSite()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function id(){return 'id-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toISOString().slice(0,10)}
function fmtDate(v){if(!v)return '';const d=new Date(v+'T00:00:00');return isNaN(d)?v:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';modalOpen=true}
function closeModal(){if(!modalOpen)return;$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.style.overflow='';modalOpen=false}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function fileData(file,max=1200){return new Promise((res,rej)=>{if(!file)return res('');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.82))};img.onerror=rej;img.src=reader.result};reader.onerror=rej;reader.readAsDataURL(file)})}
function nav(){ $('#year').textContent=new Date().getFullYear(); $('#heroSocial').innerHTML=socialHTML(true); $('#footerSocial').innerHTML=socialHTML(false)}
function setActiveNav(id){
  const target=id || (location.hash ? location.hash.slice(1) : 'home');
  $$('.desktop-nav .nav-link, #mobilePanel .nav-link').forEach(link=>{
    const href=(link.getAttribute('href')||'').replace(/^#/,'');
    link.classList.toggle('active', href===target);
    link.setAttribute('aria-current', href===target ? 'page' : 'false');
  });
}
function bindNavState(){
  const links=$$('.desktop-nav .nav-link, #mobilePanel .nav-link');
  links.forEach(link=>link.addEventListener('click',()=>{
    const target=(link.getAttribute('href')||'').replace(/^#/,'') || 'home';
    setActiveNav(target);
  }));
  window.addEventListener('hashchange',()=>setActiveNav());
  setActiveNav();
}
function socialHTML(hero){const s=db.socials;const arr=[];if(s.whatsapp)arr.push(`<a class="social-link" data-social="whatsapp" aria-label="WhatsApp" href="${esc(s.whatsapp)}" target="_blank" rel="noopener"><img src="assets/social-whatsapp.png" alt="WhatsApp" width="32" height="32" loading="eager"></a>`);if(s.instagram)arr.push(`<a class="social-link" data-social="instagram" aria-label="Instagram" href="${esc(s.instagram)}" target="_blank" rel="noopener"><img src="assets/social-instagram.png" alt="Instagram" width="32" height="32" loading="eager"></a>`);if(s.x)arr.push(`<a class="social-link" data-social="x" aria-label="X" href="${esc(s.x)}" target="_blank" rel="noopener"><img src="assets/social-x.png" alt="X" width="32" height="32" loading="eager"></a>`);if(s.facebook)arr.push(`<a class="social-link" data-social="facebook" aria-label="Facebook" href="${esc(s.facebook)}" target="_blank" rel="noopener"><img src="assets/social-facebook.png" alt="Facebook" width="32" height="32" loading="eager"></a>`);if(!arr.length)arr.push(`<span style="color:#888;font-size:11px">Social links will appear here.</span>`);return arr.join('')}
function renderSite(){nav();$('#leaderCount').textContent=String(db.leaders.length).padStart(2,'0');$('#leadersGrid').innerHTML=db.leaders.length?db.leaders.map((l,i)=>`<article class="leader-card reveal visible"><div class="leader-photo">${l.photo?`<img src="${l.photo}" alt="${esc(l.name)}" style="transform:scale(${Number(l.scale)||1});object-position:${Number(l.posX??50)}% ${Number(l.posY??50)}%">`:'<span class="photo-placeholder">✦</span>'}</div><div class="leader-info"><strong>${esc(l.name)}</strong><small>${esc(l.role)}</small><div class="micro">${esc(l.line||'')}</div></div></article>`).join(''):'<div class="empty">Leadership profiles will appear here.</div>';
$('#updatesGrid').innerHTML=db.updates.length?db.updates.map(u=>`<article class="update-card reveal visible"><time>${esc(fmtDate(u.date))}</time><div><h3>${esc(u.title)}</h3><p>${esc(u.body)}</p></div><span></span></article>`).join(''):'<div class="empty">No updates published yet.</div>';
$('#galleryGrid').innerHTML=db.gallery.length?db.gallery.map(g=>`<figure class="gallery-card reveal visible"><img src="${esc(g.src)}" alt="${esc(g.title)}"><figcaption>${esc(g.title)}</figcaption></figure>`).join(''):'<div class="empty">No gallery items published yet.</div>';
}
function login(){openModal(`<div class="login-wrap"><img src="assets/yyc-logo-clean.webp" style="width:76px;height:76px;border-radius:50%;object-fit:cover" alt="YYC"><div class="section-kicker" style="margin-top:20px">PRIVATE MANAGEMENT</div><h2 class="modal-title" id="modalTitle">YYC Admin Access</h2><p class="modal-sub">Manage members, leaders, updates, gallery, approvals and social links.</p><form id="loginForm"><div class="form-grid"><div class="field full"><label>Admin ID</label><input id="aid" autocomplete="username" placeholder="lxshhadmin" required></div><div class="field full"><label>Password</label><input id="apass" type="password" autocomplete="current-password" required></div></div><div class="form-actions"><button class="btn gold" type="submit">Enter Admin ↗</button></div></form><p class="security">GitHub Pages mode stores data in this browser. The login is a front-end demo gate, not server-side security.</p></div>`);$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const u=$('#aid').value.trim().toLowerCase(),p=$('#apass').value;if(ADMIN[u]===p){currentAdmin=u;adminPanel()}else toast('Invalid admin ID or password')})}
function adminPanel(){renderAdmin('overview')}
function renderAdmin(tab){const tabs=[['overview','Overview'],['members','Members'],['leaders','Leaders'],['updates','Updates'],['gallery','Gallery'],['approvals','Approvals'],['settings','Settings']];openModal(`<div class="admin-shell"><aside class="admin-side">${tabs.map(([idn,label])=>`<button class="${tab===idn?'active':''}" data-tab="${idn}">${label}</button>`).join('')}<button id="adminLogout">Log out</button></aside><div class="admin-main" id="adminMain"></div></div>`);$('#adminLogout').addEventListener('click',()=>{currentAdmin=null;closeModal();toast('Logged out')});$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>renderAdmin(b.dataset.tab)));adminView(tab)}
function adminView(tab){const a=$('#adminMain');const approved=db.members.filter(x=>x.status==='approved').length,pending=db.members.filter(x=>x.status==='pending').length||db.pendingMembers.length; if(tab==='overview'){a.innerHTML=`<div class="admin-top"><h2>Admin overview</h2><button class="mini-btn gold" id="backupBtn">Export backup</button></div><div class="stats"><div class="stat"><b>${approved}</b><span>Approved members</span></div><div class="stat"><b>${pending}</b><span>Pending approvals</span></div><div class="stat"><b>${db.leaders.length}</b><span>Leaders</span></div><div class="stat"><b>${db.updates.length}</b><span>Published updates</span></div></div><div class="notice" style="margin-top:16px">Signed in as <strong>${esc(currentAdmin)}</strong>. Use Approvals to review new member, update and gallery submissions.</div>`;$('#backupBtn').addEventListener('click',exportBackup);return}
if(tab==='members'){a.innerHTML=`<div class="admin-top"><h2>Members</h2><button class="mini-btn gold" id="addMember">+ Add member</button></div><div class="admin-table"><div class="admin-row" style="color:#8c939e;font-size:10px;text-transform:uppercase;letter-spacing:.12em"><div>Name</div><div>Status</div><div>Actions</div></div>${db.members.length?db.members.map((m,i)=>`<div class="admin-row"><div><strong>${esc(m.name)}</strong><div style="color:#8c939e;font-size:11px">${esc(m.roleNumber||'No role number')} · ${esc(m.phone||'')}</div></div><div style="font-size:11px;color:${m.status==='approved'?'#d7ae66':m.status==='pending'?'#fff':'#8c939e'}">${esc(m.status)}</div><div class="admin-actions"><button class="mini-btn" onclick="YYC.viewMember(${i})">View card</button>${m.status==='pending'?`<button class="mini-btn gold" onclick="YYC.approveMember(${i})">Approve</button><button class="mini-btn" onclick="YYC.denyMember(${i})">Deny</button>`:''}<button class="mini-btn" onclick="YYC.removeMember(${i})">Remove</button></div></div>`).join(''):'<div class="empty" style="margin:14px">No member records yet.</div>'}</div>`;$('#addMember').addEventListener('click',()=>memberForm(true));return}
if(tab==='leaders'){a.innerHTML=`<div class="admin-top"><h2>Leaders</h2><button class="mini-btn gold" id="addLeader">+ Add leader</button></div><div class="admin-card-list">${db.leaders.length?db.leaders.map((l,i)=>`<div class="approval-card"><div class="meta"><strong>${esc(l.name)}</strong><small>${esc(l.role)} · ${esc(l.line||'')}</small></div><div class="admin-actions"><button class="mini-btn" onclick="YYC.editLeader(${i})">Edit</button><button class="mini-btn" onclick="YYC.removeLeader(${i})">Remove</button></div></div>`).join(''):'<div class="empty">No leaders.</div>'}</div>`;$('#addLeader').addEventListener('click',()=>leaderForm());return}
if(tab==='updates'){a.innerHTML=`<div class="admin-top"><h2>Updates</h2><button class="mini-btn gold" id="addUpdate">+ Add update</button></div><div class="admin-card-list">${db.updates.length?db.updates.map((u,i)=>`<div class="approval-card"><div class="meta"><strong>${esc(u.title)}</strong><small>${esc(fmtDate(u.date))} · ${esc(u.body.slice(0,90))}${u.body.length>90?'…':''}</small></div><div class="admin-actions"><button class="mini-btn" onclick="YYC.editUpdate(${i})">Edit</button><button class="mini-btn" onclick="YYC.removeUpdate(${i})">Delete</button></div></div>`).join(''):'<div class="empty">No updates.</div>'}</div>`;$('#addUpdate').addEventListener('click',()=>updateForm());return}
if(tab==='gallery'){a.innerHTML=`<div class="admin-top"><h2>Gallery</h2><button class="mini-btn gold" id="addGallery">+ Add photo</button></div><div class="gallery-grid" style="grid-template-columns:repeat(2,1fr)">${db.gallery.length?db.gallery.map((g,i)=>`<figure class="gallery-card" style="min-height:260px"><img src="${esc(g.src)}"><figcaption>${esc(g.title)} <button class="mini-btn" style="margin-left:8px" onclick="YYC.removeGallery(${i})">Delete</button></figcaption></figure>`).join(''):'<div class="empty">No gallery.</div>'}</div>`;$('#addGallery').addEventListener('click',()=>galleryForm());return}
if(tab==='approvals'){const has=db.pendingMembers.length+db.pendingUpdates.length+db.pendingGallery.length;if(!has){a.innerHTML=`<div class="admin-top"><h2>Approvals</h2></div><div class="empty">No pending submissions.</div>`;return}a.innerHTML=`<div class="admin-top"><h2>Approvals</h2></div><div class="admin-card-list">${db.pendingMembers.map((m,i)=>`<div class="approval-card"><div class="meta"><strong>${esc(m.name)} · Member</strong><small>${esc(m.phone||'')} · ${esc(m.email||'')}</small></div><div class="admin-actions"><button class="mini-btn gold" onclick="YYC.approvePendingMember(${i})">Approve</button><button class="mini-btn" onclick="YYC.denyPendingMember(${i})">Deny</button></div></div>`).join('')}${db.pendingUpdates.map((u,i)=>`<div class="approval-card"><div class="meta"><strong>${esc(u.title)} · Update</strong><small>${esc(u.body)}</small></div><div class="admin-actions"><button class="mini-btn gold" onclick="YYC.approvePendingUpdate(${i})">Publish</button><button class="mini-btn" onclick="YYC.denyPendingUpdate(${i})">Deny</button></div></div>`).join('')}${db.pendingGallery.map((g,i)=>`<div class="approval-card"><div class="meta"><strong>${esc(g.title)} · Gallery</strong><small>Photo submission</small></div><div class="admin-actions"><button class="mini-btn gold" onclick="YYC.approvePendingGallery(${i})">Publish</button><button class="mini-btn" onclick="YYC.denyPendingGallery(${i})">Deny</button></div></div>`).join('')}</div>`;return}
if(tab==='settings'){const s=db.socials;a.innerHTML=`<div class="admin-top"><h2>Settings</h2></div><form id="settingsForm"><div class="form-grid"><div class="field"><label>Club name</label><input id="setName" value="${esc(db.settings.clubName)}"></div><div class="field"><label>Location</label><input id="setLoc" value="${esc(db.settings.location)}"></div><div class="field full"><label>Slogan</label><input id="setSlogan" value="${esc(db.settings.slogan)}"></div><div class="field"><label>Instagram URL</label><input id="setInsta" value="${esc(s.instagram)}"></div><div class="field"><label>WhatsApp URL</label><input id="setWhats" value="${esc(s.whatsapp)}"></div><div class="field"><label>X URL</label><input id="setX" value="${esc(s.x)}" placeholder="https://x.com/..."></div><div class="field"><label>Facebook URL</label><input id="setFb" value="${esc(s.facebook)}" placeholder="https://facebook.com/..."></div></div><div class="form-actions"><button class="btn gold">Save site settings</button></div></form>`;$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();db.settings.clubName=$('#setName').value.trim();db.settings.location=$('#setLoc').value.trim();db.settings.slogan=$('#setSlogan').value.trim();db.socials={instagram:$('#setInsta').value.trim(),whatsapp:$('#setWhats').value.trim(),x:$('#setX').value.trim(),facebook:$('#setFb').value.trim()};save();toast('Settings saved');adminPanel()});return}}
function cropEditor(prefix,obj){return `<div class="crop-editor"><div class="crop-preview"><img id="${prefix}Preview" src="${obj.photo||'assets/yyc-logo-clean.webp'}" style="object-position:${obj.posX}% ${obj.posY}%;transform:scale(${obj.scale})" alt="preview"></div><div class="crop-controls"><div class="range-row"><label>Zoom</label><input id="${prefix}Scale" type="range" min="1" max="2.5" step="0.01" value="${obj.scale}"><output id="${prefix}ScaleOut">${obj.scale.toFixed(2)}×</output></div><div class="range-row"><label>Left/Right</label><input id="${prefix}X" type="range" min="0" max="100" step="1" value="${obj.posX}"><output id="${prefix}XOut">${obj.posX}%</output></div><div class="range-row"><label>Up/Down</label><input id="${prefix}Y" type="range" min="0" max="100" step="1" value="${obj.posY}"><output id="${prefix}YOut">${obj.posY}%</output></div><div class="notice">Adjust the photo before saving. The same framing will be used on the public profile or membership card.</div></div></div>`}
function wireCrop(prefix,obj,fileId){const upd=()=>{obj.scale=+$('#'+prefix+'Scale').value;obj.posX=+$('#'+prefix+'X').value;obj.posY=+$('#'+prefix+'Y').value;$('#'+prefix+'Preview').style.transform=`scale(${obj.scale})`;$('#'+prefix+'Preview').style.objectPosition=`${obj.posX}% ${obj.posY}%`;$('#'+prefix+'ScaleOut').value='';$('#'+prefix+'ScaleOut').textContent=obj.scale.toFixed(2)+'×';$('#'+prefix+'XOut').textContent=obj.posX+'%';$('#'+prefix+'YOut').textContent=obj.posY+'%'};['Scale','X','Y'].forEach(k=>$('#'+prefix+k).addEventListener('input',upd));$('#'+fileId).addEventListener('change',async()=>{const data=await fileData($('#'+fileId).files[0]);if(data){obj.photo=data;$('#'+prefix+'Preview').src=data}})}
function leaderForm(index=null){const l=index==null?{id:id(),name:'',role:'',line:'YUVAKESARI YOUTH CLUB · SUBRAHMANYA',photo:'',scale:1,posX:50,posY:50}:deep(db.leaders[index]);openModal(`<h2 class="modal-title">${index==null?'Add':'Edit'} leader</h2><form id="leaderForm"><div class="form-grid"><div class="field"><label>Name</label><input id="ln" value="${esc(l.name)}" required></div><div class="field"><label>Role</label><input id="lr" value="${esc(l.role)}" required></div><div class="field full"><label>Club line</label><input id="ll" value="${esc(l.line)}"></div><div class="field full"><label>Photo</label><input id="lf" type="file" accept="image/*"></div></div>${cropEditor('l',l,'lf')}<div class="form-actions"><button class="btn gold">Save leader</button></div></form>`);wireCrop('l',l,'lf');$('#leaderForm').addEventListener('submit',e=>{e.preventDefault();l.name=$('#ln').value.trim();l.role=$('#lr').value.trim();l.line=$('#ll').value.trim();if(index==null)db.leaders.push(l);else db.leaders[index]=l;save();toast('Leader saved');adminPanel()})}
function memberForm(adminCreate=false){const m={id:id(),name:'',dob:'',phone:'',email:'',role:'Member',club:'Yuvakesari Youth Club',photo:'',scale:1,posX:50,posY:50,status:adminCreate?'approved':'pending',roleNumber:''};openModal(`<h2 class="modal-title">Member registration</h2><p class="modal-sub">${adminCreate?'Create an approved member directly.':'Submit your details for admin review. Approved members receive a unique role number and digital membership card.'}</p><form id="memberForm"><div class="form-grid"><div class="field"><label>Full name</label><input id="mn" required></div><div class="field"><label>Date of birth</label><input id="md" type="date" required></div><div class="field"><label>Phone</label><input id="mp" required></div><div class="field"><label>Email</label><input id="me" type="email"></div><div class="field"><label>Preferred role</label><input id="mr" value="Member"></div><div class="field"><label>Club name</label><input id="mc" value="Yuvakesari Youth Club"></div><div class="field full"><label>Photo</label><input id="mf" type="file" accept="image/*" required></div></div>${cropEditor('m',m,'mf')}<div class="form-actions"><button class="btn gold">${adminCreate?'Create member':'Submit application'}</button></div></form>`);wireCrop('m',m,'mf');$('#memberForm').addEventListener('submit',async e=>{e.preventDefault();m.name=$('#mn').value.trim();m.dob=$('#md').value;m.phone=$('#mp').value.trim();m.email=$('#me').value.trim();m.role=$('#mr').value.trim();m.club=$('#mc').value.trim();if(!m.photo)return toast('Choose a photo');if(adminCreate){m.roleNumber=nextRole();m.status='approved';db.members.push(m)}else{m.status='pending';db.pendingMembers.push(m)}save();closeModal();toast(adminCreate?'Member created':'Application sent for admin review')})}
function nextRole(){const nums=db.members.concat(db.pendingMembers).map(m=>String(m.roleNumber||'')).map(x=>parseInt(x.split('-').pop(),10)).filter(Number.isFinite);return `YYC-${new Date().getFullYear()}-${String((Math.max(0,...nums)+1)).padStart(4,'0')}`}
function updateForm(index=null){const u=index==null?{id:id(),title:'',body:'',date:today()}:deep(db.updates[index]);openModal(`<h2 class="modal-title">${index==null?'Add':'Edit'} update</h2><form id="updateForm"><div class="form-grid"><div class="field"><label>Title</label><input id="ut" value="${esc(u.title)}" required></div><div class="field"><label>Date</label><input id="ud" type="date" value="${esc(u.date)}" required></div><div class="field full"><label>Message</label><textarea id="ub" required>${esc(u.body)}</textarea></div></div><div class="form-actions"><button class="btn gold">Save update</button></div></form>`);$('#updateForm').addEventListener('submit',e=>{e.preventDefault();u.title=$('#ut').value.trim();u.date=$('#ud').value;u.body=$('#ub').value.trim();if(index==null)db.updates.unshift(u);else db.updates[index]=u;save();toast('Update saved');adminPanel()})}
function galleryForm(){const g={id:id(),title:'',src:''};openModal(`<h2 class="modal-title">Add gallery photo</h2><form id="galleryForm"><div class="form-grid"><div class="field full"><label>Caption</label><input id="gt" required></div><div class="field full"><label>Image</label><input id="gf" type="file" accept="image/*" required></div></div><div class="crop-preview" style="width:100%;height:250px"><img id="gPreview" src="assets/yyc-logo-clean.webp" alt="preview"></div><div class="form-actions"><button class="btn gold">Publish photo</button></div></form>`);$('#gf').addEventListener('change',async()=>{g.src=await fileData($('#gf').files[0]);if(g.src)$('#gPreview').src=g.src});$('#galleryForm').addEventListener('submit',e=>{e.preventDefault();if(!g.src)return toast('Choose an image');g.title=$('#gt').value.trim();db.gallery.unshift(g);save();toast('Gallery photo published');adminPanel()})}
function editLeader(i){leaderForm(i)}function editUpdate(i){updateForm(i)}function removeLeader(i){if(confirm('Remove this leader?')){db.leaders.splice(i,1);save();toast('Leader removed');adminPanel()}}function removeUpdate(i){if(confirm('Delete this update?')){db.updates.splice(i,1);save();toast('Update deleted');adminPanel()}}function removeGallery(i){if(confirm('Delete this gallery photo?')){db.gallery.splice(i,1);save();toast('Gallery photo deleted');adminPanel()}}function removeMember(i){if(confirm('Remove this member record?')){db.members.splice(i,1);save();toast('Member removed');adminPanel()}}
function approveMember(i){const m=db.members[i];m.status='approved';if(!m.roleNumber)m.roleNumber=nextRole();save();toast('Member approved');adminPanel('members')}
function denyMember(i){db.members[i].status='denied';save();toast('Member denied');adminPanel('members')}
function viewMember(i){const m=db.members[i];openModal(`<div class="section-kicker">DIGITAL MEMBERSHIP CARD</div><div class="membership" style="margin-top:15px"><div class="membership-photo"><img src="${esc(m.photo)}" alt="${esc(m.name)}" style="transform:scale(${m.scale||1});object-position:${m.posX||50}% ${m.posY||50}%"></div><div><div class="section-kicker">YUVAKESARI YOUTH CLUB</div><h3>${esc(m.name)}</h3><div class="role-num">${esc(m.roleNumber||'PENDING APPROVAL')}</div><div style="color:#a8adb7;margin-top:7px">${esc(m.role||'Member')} · ${esc(m.club||'')}</div></div></div><div class="form-actions"><button class="btn outline" id="closeCard">Close</button></div>`);$('#closeCard').addEventListener('click',closeModal)}
function approvePendingMember(i){const m=db.pendingMembers.splice(i,1)[0];m.status='approved';m.roleNumber=nextRole();db.members.push(m);save();toast('Member approved and role number assigned');adminPanel('approvals')}
function denyPendingMember(i){db.pendingMembers.splice(i,1);save();toast('Member application denied');adminPanel('approvals')}
function submitUpdate(){const u={id:id(),title:'',body:'',date:today()};openModal(`<h2 class="modal-title">Submit an update</h2><p class="modal-sub">Your update will go to admin approval.</p><form id="submitUpdateForm"><div class="form-grid"><div class="field"><label>Title</label><input id="sut" required></div><div class="field"><label>Date</label><input id="sud" type="date" value="${today()}"></div><div class="field full"><label>Message</label><textarea id="sub" required></textarea></div></div><div class="form-actions"><button class="btn gold">Send for approval</button></div></form>`);$('#submitUpdateForm').addEventListener('submit',e=>{e.preventDefault();u.title=$('#sut').value.trim();u.body=$('#sub').value.trim();u.date=$('#sud').value;db.pendingUpdates.unshift(u);save();closeModal();toast('Update sent to admin approval queue')})}
function submitGallery(){const g={id:id(),title:'',src:''};openModal(`<h2 class="modal-title">Submit gallery item</h2><p class="modal-sub">Your photo will go to admin approval.</p><form id="submitGalleryForm"><div class="form-grid"><div class="field full"><label>Caption</label><input id="sgt" required></div><div class="field full"><label>Photo</label><input id="sgf" type="file" accept="image/*" required></div></div><div class="crop-preview" style="width:100%;height:250px"><img id="sgPreview" src="assets/yyc-logo-clean.webp"></div><div class="form-actions"><button class="btn gold">Send for approval</button></div></form>`);$('#sgf').addEventListener('change',async()=>{g.src=await fileData($('#sgf').files[0]);if(g.src)$('#sgPreview').src=g.src});$('#submitGalleryForm').addEventListener('submit',e=>{e.preventDefault();if(!g.src)return toast('Choose a photo');g.title=$('#sgt').value.trim();db.pendingGallery.unshift(g);save();closeModal();toast('Gallery item sent for admin approval')})}
function approvePendingUpdate(i){db.updates.unshift(db.pendingUpdates.splice(i,1)[0]);save();toast('Update published');adminPanel('approvals')}function denyPendingUpdate(i){db.pendingUpdates.splice(i,1);save();toast('Update denied');adminPanel('approvals')}function approvePendingGallery(i){db.gallery.unshift(db.pendingGallery.splice(i,1)[0]);save();toast('Gallery photo published');adminPanel('approvals')}function denyPendingGallery(i){db.pendingGallery.splice(i,1);save();toast('Gallery submission denied');adminPanel('approvals')}
function exportBackup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yuvakesari-youth-club-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function setup(){
 $('#adminOpenBtn').addEventListener('click',login);$('#adminOpenMobile').addEventListener('click',()=>{closeMobile();login()});$('#footerAdminBtn').addEventListener('click',login);$('#memberRegisterBtn').addEventListener('click',()=>memberForm(false));$('#submitUpdateBtn').addEventListener('click',submitUpdate);$('#submitGalleryBtn').addEventListener('click',submitGallery);
 $('#menuBtn').addEventListener('click',()=>{$('#mobilePanel').classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',$('#mobilePanel').classList.contains('open'))});$$('#mobilePanel a').forEach(a=>a.addEventListener('click',closeMobile));bindNavState();$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeMobile()}});observeReveals();renderSite();
}
function closeMobile(){$('#mobilePanel').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false')}
function observeReveals(){const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08}):null;if(io)$$('.reveal').forEach(el=>io.observe(el));else $$('.reveal').forEach(el=>el.classList.add('visible'))}
window.YYC={viewMember,approveMember,denyMember,removeMember,editLeader,removeLeader,editUpdate,removeUpdate,removeGallery,approvePendingMember,denyPendingMember,approvePendingUpdate,denyPendingUpdate,approvePendingGallery,denyPendingGallery};
setup();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
