'use strict';
const KEY='yyc_v2';
const ADMIN_USERS={lxshhisadmin:['lxshhisadmin','YYC@2026'],lxshhisboss:['lxshhisboss','YYC@2026']};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const today=()=>new Date().toISOString().slice(0,10);
const defaults={
 leaders:[{id:1,name:'AHWIN Y',role:'PRESIDENT',place:'YUVAKESARI YOUTH CLUB • SUBRAHMANYA',photo:'',scale:1,posX:50,posY:50}],
 updates:[{id:1,title:'Welcome to Yuvakesari Youth Club',body:'Community, youth energy and meaningful action — together from Subrahmanya.',date:today()}],
 gallery:[{id:1,title:'Tulunadu • Subrahmanya',src:'assets/hero-tulunad.png'}],members:[],pendingUpdates:[],pendingGallery:[]
};
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')return Object.assign(clone(defaults),x)}catch(e){}return clone(defaults)}
let db=load(), currentAdmin=null, activeTab='overview';
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(){ $('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open') }
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2400)}
function fileToDataURL(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function renderAll(){
 $('#year').textContent=new Date().getFullYear();
 $('#leaderCount').textContent=String(db.leaders.length).padStart(2,'0');
 $('#leadersGrid').innerHTML=db.leaders.map(l=>`<article class="leader-card reveal visible"><div class="leader-photo">${l.photo?`<img src="${l.photo}" style="transform:scale(${Number(l.scale)||1});object-position:${Number(l.posX)||50}% ${Number(l.posY)||50}%" alt="${esc(l.name)}">`:'<span class="photo-placeholder">✦</span>'}</div><div class="leader-info"><strong>${esc(l.name)}</strong><small>${esc(l.role)}</small><div class="micro">${esc(l.place||'')}</div></div></article>`).join('')||empty('Leadership profiles will appear here.');
 $('#updatesGrid').innerHTML=db.updates.map(u=>`<article class="update-card reveal visible"><time>${esc(u.date)}</time><h3>${esc(u.title)}</h3><p>${esc(u.body)}</p></article>`).join('')||empty('No updates yet.');
 $('#galleryGrid').innerHTML=db.gallery.map(g=>`<figure class="gallery-card reveal visible"><img src="${g.src}" alt="${esc(g.title)}"><figcaption>${esc(g.title)}</figcaption></figure>`).join('')||empty('No gallery items yet.');
}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function login(){openModal(`<div class="login-box"><img src="assets/yyc-logo.png" class="login-logo" alt="YYC"><div class="section-kicker">PRIVATE MANAGEMENT</div><h2 class="modal-title">YYC Admin Access</h2><p class="modal-sub">Manage members, leaders, updates, gallery and approvals.</p><form id="loginForm"><div class="form-grid"><div class="field full"><label>Admin ID</label><input id="aid" autocomplete="username" required placeholder="lxshhisadmin"></div><div class="field full"><label>Password</label><input id="apass" type="password" autocomplete="current-password" required></div></div><div class="form-actions"><button type="submit" class="btn primary">Enter Admin</button></div></form><p class="security-note">Static GitHub Pages mode: data is stored in this browser. For a shared public database, connect Firebase or Supabase.</p></div>`);$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#aid').value.trim().toLowerCase(),pw=$('#apass').value;if(ADMIN_USERS[id]&&ADMIN_USERS[id].includes(pw)){currentAdmin=id;activeTab='overview';renderAdmin()}else toast('Invalid admin ID or password')})}
function renderAdmin(){
 const tabs=[['overview','Overview'],['members','Members'],['leaders','Leaders'],['updates','Updates'],['gallery','Gallery'],['approvals','Approvals']];
 let body='';
 if(activeTab==='overview') body=`<div class="admin-top"><div><div class="section-kicker">ADMIN DASHBOARD</div><h3>Control Center</h3></div><span class="admin-chip">SIGNED IN • ${esc(currentAdmin)}</span></div><div class="stats-grid"><div><b>${db.members.filter(m=>m.status==='approved').length}</b><span>Approved members</span></div><div><b>${db.members.filter(m=>m.status==='pending').length}</b><span>Pending members</span></div><div><b>${db.leaders.length}</b><span>Leaders</span></div><div><b>${db.pendingUpdates.length+db.pendingGallery.length}</b><span>Content awaiting approval</span></div></div><div class="quick-grid"><button onclick="setTab('members')">Manage members →</button><button onclick="setTab('leaders')">Manage leaders →</button><button onclick="setTab('updates')">Manage updates →</button><button onclick="setTab('gallery')">Manage gallery →</button><button onclick="setTab('approvals')">Review approvals →</button><button onclick="backupData()">Export backup ↓</button></div>`;
 if(activeTab==='members') body=membersAdmin();
 if(activeTab==='leaders') body=leadersAdmin();
 if(activeTab==='updates') body=updatesAdmin();
 if(activeTab==='gallery') body=galleryAdmin();
 if(activeTab==='approvals') body=approvalsAdmin();
 openModal(`<div class="admin-shell"><aside class="admin-side"><div class="admin-side-brand"><img src="assets/yyc-logo.png"><span>YYC ADMIN</span></div>${tabs.map(t=>`<button class="${activeTab===t[0]?'active':''}" onclick="setTab('${t[0]}')">${t[1]}</button>`).join('')}<button onclick="backupData()">Export backup</button><button onclick="currentAdmin=null;closeModal()">Sign out</button></aside><section class="admin-main">${body}</section></div>`)
}
function membersAdmin(){return `<div class="admin-top"><div><div class="section-kicker">MEMBERS</div><h3>Member records</h3></div><button class="mini-btn ok" onclick="registerMember(true)">+ Add member</button></div><div class="admin-list">${db.members.map((m,i)=>`<div class="admin-item"><div class="admin-member"><div class="mini-avatar">${m.photo?`<img src="${m.photo}">`:'✦'}</div><div><strong>${esc(m.name)}</strong><small>${esc(m.roleNumber||'Pending role number')} • ${esc(m.status||'pending')}</small></div></div><div class="admin-item-actions">${m.status==='pending'?`<button class="mini-btn ok" onclick="approveMember(${i})">Approve</button><button class="mini-btn danger" onclick="denyMember(${i})">Deny</button>`:''}<button class="mini-btn" onclick="viewMember(${i})">Card</button><button class="mini-btn danger" onclick="removeMember(${i})">Remove</button></div></div>`).join('')||empty('No member records yet.')}</div>`}
function leadersAdmin(){return `<div class="admin-top"><div><div class="section-kicker">LEADERS</div><h3>Leadership profiles</h3></div><button class="mini-btn ok" onclick="leaderForm()">+ Add leader</button></div><div class="admin-list">${db.leaders.map((l,i)=>`<div class="admin-item"><div class="admin-member"><div class="mini-avatar">${l.photo?`<img src="${l.photo}">`:'✦'}</div><div><strong>${esc(l.name)}</strong><small>${esc(l.role)}</small></div></div><div class="admin-item-actions"><button class="mini-btn" onclick="leaderForm(${i})">Edit</button><button class="mini-btn danger" onclick="removeLeader(${i})">Remove</button></div></div>`).join('')||empty('No leaders yet.')}</div>`}
function updatesAdmin(){return `<div class="admin-top"><div><div class="section-kicker">UPDATES</div><h3>Published updates</h3></div><button class="mini-btn ok" onclick="updateForm()">+ Add update</button></div><div class="admin-list">${db.updates.map((u,i)=>`<div class="admin-item"><div><strong>${esc(u.title)}</strong><small>${esc(u.date)} • ${esc(u.body).slice(0,100)}</small></div><div class="admin-item-actions"><button class="mini-btn" onclick="updateForm(${i})">Edit</button><button class="mini-btn danger" onclick="removeUpdate(${i})">Delete</button></div></div>`).join('')||empty('No updates yet.')}</div>`}
function galleryAdmin(){return `<div class="admin-top"><div><div class="section-kicker">GALLERY</div><h3>Published gallery</h3></div><button class="mini-btn ok" onclick="galleryForm()">+ Add gallery</button></div><div class="admin-list">${db.gallery.map((g,i)=>`<div class="admin-item"><div class="admin-member"><div class="mini-avatar">${g.src?`<img src="${g.src}">`:'✦'}</div><div><strong>${esc(g.title)}</strong><small>Published</small></div></div><button class="mini-btn danger" onclick="removeGallery(${i})">Delete</button></div>`).join('')||empty('No gallery items yet.')}</div>`}
function approvalsAdmin(){return `<div class="admin-top"><div><div class="section-kicker">APPROVAL QUEUE</div><h3>Review submissions</h3></div><span class="admin-chip">${db.pendingUpdates.length+db.pendingGallery.length} waiting</span></div><div class="admin-list">${db.pendingUpdates.map((u,i)=>`<div class="admin-item"><div><strong>UPDATE • ${esc(u.title)}</strong><small>${esc(u.body)}</small></div><div class="admin-item-actions"><button class="mini-btn ok" onclick="approveUpdate(${i})">Publish</button><button class="mini-btn danger" onclick="denyUpdate(${i})">Deny</button></div></div>`).join('')}${db.pendingGallery.map((g,i)=>`<div class="admin-item"><div class="admin-member"><div class="mini-avatar"><img src="${g.src}"></div><div><strong>GALLERY • ${esc(g.title)}</strong><small>Photo submission</small></div></div><div class="admin-item-actions"><button class="mini-btn ok" onclick="approveGallery(${i})">Publish</button><button class="mini-btn danger" onclick="denyGallery(${i})">Deny</button></div></div>`).join('')}${!db.pendingUpdates.length&&!db.pendingGallery.length?empty('Nothing waiting for approval.'):''}</div>`}
function setTab(t){activeTab=t;renderAdmin()}
function cropEditor(prefix,obj,imgId,fileId){return `<div class="crop-editor"><div class="crop-preview"><img id="${imgId}" src="${obj.photo||'assets/yyc-logo.png'}"></div><div><div class="range-row"><label>Zoom</label><input id="${prefix}s" type="range" min="1" max="2.5" step=".01" value="${obj.scale||1}"><output id="${prefix}so">${obj.scale||1}×</output></div><div class="range-row"><label>Left / Right</label><input id="${prefix}x" type="range" min="0" max="100" value="${obj.posX??50}"><output id="${prefix}xo">${obj.posX??50}%</output></div><div class="range-row"><label>Up / Down</label><input id="${prefix}y" type="range" min="0" max="100" value="${obj.posY??50}"><output id="${prefix}yo">${obj.posY??50}%</output></div></div></div>`}
function wireCrop(prefix,obj,imgId,fileId){const img=$('#'+imgId), f=$('#'+fileId), s=$('#'+prefix+'s'),x=$('#'+prefix+'x'),y=$('#'+prefix+'y');f?.addEventListener('change',async()=>{obj.photo=await fileToDataURL(f.files[0]);img.src=obj.photo});const up=()=>{img.style.transform=`scale(${s.value})`;img.style.objectPosition=`${x.value}% ${y.value}%`;$('#'+prefix+'so').value=s.value+'×';$('#'+prefix+'xo').value=x.value+'%';$('#'+prefix+'yo').value=y.value+'%'};[s,x,y].forEach(z=>z.addEventListener('input',up));up()}
function leaderForm(i=null){const l=i===null?{name:'',role:'',place:'',photo:'',scale:1,posX:50,posY:50}:clone(db.leaders[i]);openModal(`<h2 class="modal-title">${i===null?'Add':'Edit'} leader</h2><p class="modal-sub">Add a leader and adjust the photo crop before saving.</p><form id="leaderForm"><div class="form-grid"><div class="field"><label>Name</label><input id="ln" value="${esc(l.name)}" required></div><div class="field"><label>Role</label><input id="lr" value="${esc(l.role)}" required></div><div class="field full"><label>Club line</label><input id="lp" value="${esc(l.place)}"></div><div class="field full"><label>Portrait</label><input id="lfile" type="file" accept="image/*"></div></div>${cropEditor('l',l,'cropImg','lfile')}<div class="form-actions"><button type="submit" class="btn primary">Save leader</button></div></form>`);wireCrop('l',l,'cropImg','lfile');$('#leaderForm').addEventListener('submit',e=>{e.preventDefault();l.name=$('#ln').value.trim();l.role=$('#lr').value.trim();l.place=$('#lp').value.trim();l.scale=+$('#ls').value;l.posX=+$('#lx').value;l.posY=+$('#ly').value;if(i===null){l.id=Date.now();db.leaders.push(l)}else db.leaders[i]=l;save();closeModal();toast('Leader saved')})}
function registerMember(adminAdd=false){const m={name:'',dob:'',phone:'',email:'',role:'Member',club:'Yuvakesari Youth Club',photo:'',scale:1,posX:50,posY:50,status:adminAdd?'approved':'pending',roleNumber:''};openModal(`<h2 class="modal-title">Member registration</h2><p class="modal-sub">${adminAdd?'Create a member directly from admin.':'Submit your details for admin approval. Approved members receive a role number and membership card.'}</p><form id="memberForm"><div class="form-grid"><div class="field"><label>Full name</label><input id="mn" required></div><div class="field"><label>Date of birth</label><input id="md" type="date" required></div><div class="field"><label>Phone</label><input id="mp" required></div><div class="field"><label>Email</label><input id="me" type="email"></div><div class="field"><label>Preferred role</label><input id="mr" value="Member"></div><div class="field"><label>Club name</label><input id="mc" value="Yuvakesari Youth Club"></div><div class="field full"><label>Photo</label><input id="mf" type="file" accept="image/*" required></div></div>${cropEditor('m',m,'mimg','mf')}<div class="form-actions"><button type="submit" class="btn primary">${adminAdd?'Create member':'Submit for approval'}</button></div></form>`);wireCrop('m',m,'mimg','mf');$('#memberForm').addEventListener('submit',async e=>{e.preventDefault();if(!m.photo)return toast('Please choose a photo');Object.assign(m,{name:$('#mn').value.trim(),dob:$('#md').value,phone:$('#mp').value.trim(),email:$('#me').value.trim(),role:$('#mr').value.trim(),club:$('#mc').value.trim(),scale:+$('#ms').value,posX:+$('#mx').value,posY:+$('#my').value,id:Date.now()});if(adminAdd){m.roleNumber=nextRole();m.status='approved'}db.members.push(m);save();closeModal();toast(adminAdd?'Member created':'Registration submitted for approval')})}
function nextRole(){const nums=db.members.map(m=>parseInt(String(m.roleNumber||'').split('-').pop(),10)).filter(Number.isFinite);return `YYC-${new Date().getFullYear()}-${String((Math.max(0,...nums)+1)).padStart(4,'0')}`}
function approveMember(i){db.members[i].status='approved';if(!db.members[i].roleNumber)db.members[i].roleNumber=nextRole();save();toast('Member approved • role number assigned')}
function denyMember(i){db.members[i].status='denied';save();toast('Member denied')}
function removeMember(i){if(confirm('Remove this member record?')){db.members.splice(i,1);save();toast('Member removed')}}
function viewMember(i){const m=db.members[i];openModal(`<div class="card-wrap"><div class="section-kicker">YYC MEMBERSHIP CARD</div><div class="membership-card"><div class="member-photo"><img src="${m.photo}" style="transform:scale(${m.scale||1});object-position:${m.posX??50}% ${m.posY??50}%"></div><div><div class="card-logo">YUVAKESARI</div><div class="card-sub">YOUTH CLUB • SUBRAHMANYA</div><h3>${esc(m.name)}</h3><b>${esc(m.roleNumber||'PENDING APPROVAL')}</b><small>${esc(m.role||'Member')}</small></div></div><div class="form-actions"><button class="btn ghost" onclick="closeModal()">Close</button></div></div>`)}
function updateForm(i=null){const u=i===null?{title:'',body:'',date:today()}:clone(db.updates[i]);openModal(`<h2 class="modal-title">${i===null?'Add':'Edit'} update</h2><form id="uf"><div class="form-grid"><div class="field"><label>Title</label><input id="ut" value="${esc(u.title)}" required></div><div class="field"><label>Date</label><input id="ud" type="date" value="${esc(u.date)}" required></div><div class="field full"><label>Message</label><textarea id="ub" required>${esc(u.body)}</textarea></div></div><div class="form-actions"><button class="btn primary">Publish update</button></div></form>`);$('#uf').addEventListener('submit',e=>{e.preventDefault();u.title=$('#ut').value.trim();u.date=$('#ud').value;u.body=$('#ub').value.trim();if(i===null){u.id=Date.now();db.updates.unshift(u)}else db.updates[i]=u;save();closeModal();toast('Update published')})}
function removeUpdate(i){if(confirm('Delete this update?')){db.updates.splice(i,1);save();toast('Update deleted')}}
function galleryForm(){const g={title:'',src:''};openModal(`<h2 class="modal-title">Add gallery item</h2><form id="gf"><div class="form-grid"><div class="field full"><label>Title</label><input id="gt" required placeholder="Event / place / activity"></div><div class="field full"><label>Image</label><input id="gfile" type="file" accept="image/*" required></div></div><div id="galleryPreview" class="upload-preview"><img src="assets/yyc-logo.png"></div><div class="form-actions"><button class="btn primary">Publish gallery</button></div></form>`);$('#gfile').addEventListener('change',async()=>{g.src=await fileToDataURL($('#gfile').files[0]);$('#galleryPreview img').src=g.src});$('#gf').addEventListener('submit',e=>{e.preventDefault();if(!g.src)return toast('Choose an image');g.title=$('#gt').value.trim();g.id=Date.now();db.gallery.unshift(g);save();closeModal();toast('Gallery item published')})}
function removeGallery(i){if(confirm('Delete this gallery item?')){db.gallery.splice(i,1);save();toast('Gallery item deleted')}}
function submitUpdate(){const u={title:'',body:'',date:today()};openModal(`<h2 class="modal-title">Submit an update</h2><p class="modal-sub">This goes to the admin approval queue.</p><form id="suf"><div class="form-grid"><div class="field"><label>Title</label><input id="sut" required></div><div class="field"><label>Date</label><input id="sud" type="date" value="${today()}"></div><div class="field full"><label>Message</label><textarea id="sub" required></textarea></div></div><div class="form-actions"><button class="btn primary">Send for approval</button></div></form>`);$('#suf').addEventListener('submit',e=>{e.preventDefault();u.id=Date.now();u.title=$('#sut').value.trim();u.date=$('#sud').value;u.body=$('#sub').value.trim();db.pendingUpdates.unshift(u);save();closeModal();toast('Sent to admin approval queue')})}
function submitGallery(){const g={title:'',src:''};openModal(`<h2 class="modal-title">Submit gallery item</h2><p class="modal-sub">Upload a photo for admin approval.</p><form id="sgf"><div class="form-grid"><div class="field full"><label>Caption</label><input id="sgt" required></div><div class="field full"><label>Photo</label><input id="sgfile" type="file" accept="image/*" required></div></div><div id="submitGalleryPreview" class="upload-preview"><img src="assets/yyc-logo.png"></div><div class="form-actions"><button class="btn primary">Send for approval</button></div></form>`);$('#sgfile').addEventListener('change',async()=>{g.src=await fileToDataURL($('#sgfile').files[0]);$('#submitGalleryPreview img').src=g.src});$('#sgf').addEventListener('submit',e=>{e.preventDefault();if(!g.src)return toast('Choose an image');g.id=Date.now();g.title=$('#sgt').value.trim();db.pendingGallery.unshift(g);save();closeModal();toast('Gallery item sent for approval')})}
function approveUpdate(i){const x=db.pendingUpdates.splice(i,1)[0];db.updates.unshift(x);save();toast('Update published')}
function denyUpdate(i){db.pendingUpdates.splice(i,1);save();toast('Update denied')}
function approveGallery(i){const x=db.pendingGallery.splice(i,1)[0];db.gallery.unshift(x);save();toast('Gallery item published')}
function denyGallery(i){db.pendingGallery.splice(i,1);save();toast('Gallery item denied')}
function backupData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yyc-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));$('#openAdmin').addEventListener('click',login);$('#footerAdmin').addEventListener('click',login);$('#openRegister').addEventListener('click',()=>registerMember(false));$('#submitUpdateBtn').addEventListener('click',submitUpdate);$('#submitGalleryBtn').addEventListener('click',submitGallery);$('#navToggle').addEventListener('click',()=>$('#mainNav').classList.toggle('open'));$$('#mainNav a').forEach(a=>a.addEventListener('click',()=>$('#mainNav').classList.remove('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const io='IntersectionObserver' in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08}):null;if(io)$$('.reveal').forEach(x=>io.observe(x));else $$('.reveal').forEach(x=>x.classList.add('visible'));
window.setTab=setTab;window.registerMember=registerMember;window.leaderForm=leaderForm;window.updateForm=updateForm;window.galleryForm=galleryForm;window.approveMember=approveMember;window.denyMember=denyMember;window.removeMember=removeMember;window.viewMember=viewMember;window.removeLeader=i=>{if(confirm('Remove this leader?')){db.leaders.splice(i,1);save();toast('Leader removed')}};window.removeUpdate=removeUpdate;window.removeGallery=removeGallery;window.approveUpdate=approveUpdate;window.denyUpdate=denyUpdate;window.approveGallery=approveGallery;window.denyGallery=denyGallery;window.backupData=backupData;
renderAll();
