const STATIC_MODE = !['localhost','127.0.0.1','::1'].includes(location.hostname);
const STORAGE_KEY='yyc_database_v18';
const ADMIN_KEY='yyc_admin_session_v18';
const ADMIN_ID='lxshhadmin';
const ADMIN_PASSWORD='lxshhboss';

const defaultSettings={
  siteName:'Yuvakesari Youth Club',formerName:'Formerly Yuvakesari Kukke',location:'Subrahmanya, Karnataka',
  heroKicker:'TOGETHER WE GROW',heroTagline:'Empowering youth, building a better tomorrow through service, unity and social responsibility.',
  quote:'Small steps create big changes.',mission:'YUVAKESARI YOUTH CLUB (FORMERLY YUVAKESARI KUKKE) IS A NON PROFIT ORGANIZATION MEANT FOR CONDUCTING VARIOUS SOCIAL ACTIVITIES LIKE SWACHH ABHIYAAN, GAMES OR EVENTS ETC.',
  thanks:'THANKING YOU',president:'ASHWIN Y',presidentTitle:'THE PRESIDENT',footerLine:'Yuvakesari Youth Club · Subrahmanya'
};
const defaultData={members:[],leaders:[{id:1,name:'Arjun Nair',role:'President',photo:'',photoZoom:1,photoX:50,photoY:50},{id:2,name:'Meera Menon',role:'Vice President',photo:'',photoZoom:1,photoX:50,photoY:50},{id:3,name:'Vivek Kumar',role:'Secretary',photo:'',photoZoom:1,photoX:50,photoY:50}],announcements:[{id:1,date:'14 Sep 2026',title:'Community cleanup drive',body:'Meet at the central park gate at 7:00 AM. Gloves and refreshments will be provided.'},{id:2,date:'21 Sep 2026',title:'Youth cultural evening',body:'An evening of talent, music, and stories from our community.'},{id:3,date:'05 Oct 2026',title:'Member orientation',body:'A warm welcome and introduction for our newest Yuvakesari members.'}],gallery:[{id:1,title:'Community clean-up',position:0,photo:''},{id:2,title:'Cultural celebration',position:1,photo:''},{id:3,title:'Leadership workshop',position:2,photo:''},{id:4,title:'Together for change',position:3,photo:''}],settings:defaultSettings};
let publicData={leaders:[],announcements:[],gallery:[],settings:{...defaultSettings}};
let adminState={tab:'overview',summary:null,members:{rows:[],page:1,pages:1,total:0,search:'',status:'all'},leaders:{rows:[]},announcements:{rows:[],page:1,pages:1,total:0,search:''},gallery:{rows:[],page:1,pages:1,total:0,search:''},settings:{...defaultSettings}};
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>String(n||'').split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const clamp=(v,f,min,max)=>{const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):f};
const imageFallback=(img,f='./assets/lion-symbol.webp')=>{img.onerror=()=>{img.onerror=null;img.src=f}};
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(x?.members&&x?.leaders&&x?.announcements&&x?.gallery)return {...x,settings:{...defaultSettings,...(x.settings||{})}}}catch{}const x=clone(defaultData);localStorage.setItem(STORAGE_KEY,JSON.stringify(x));return x}
let localDB=STATIC_MODE?loadLocal():null;
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(localDB))}
function localPage(type,page,size,search,status){let arr=localDB[type]||[];const q=String(search||'').toLowerCase().trim();if(q)arr=arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(type==='members'&&status&&status!=='all')arr=arr.filter(x=>x.status===status);const total=arr.length,pages=Math.max(1,Math.ceil(total/size));const p=Math.min(Math.max(1,Number(page)||1),pages);return{rows:clone(arr.slice((p-1)*size,p*size)),page:p,pageSize:size,total,pages}}
function requireLocalAdmin(){if(sessionStorage.getItem(ADMIN_KEY)!=='1')throw new Error('Admin sign-in required.')}
async function staticApi(endpoint,opts={}){const method=(opts.method||'GET').toUpperCase();let body={};try{body=opts.body?JSON.parse(opts.body):{}}catch{throw new Error('Invalid request data.')}if(endpoint==='member-status'&&method==='GET'){const u=new URL('http://x/'+endpoint),role=(u.searchParams.get('role')||'').trim().toUpperCase(),phone=(u.searchParams.get('phone')||'').trim();const item=localDB.members.find(x=>String(x.role||'').toUpperCase()===role&&String(x.phone||'').trim()===phone);if(!item)throw new Error('Application not found. Check your role number and phone number.');return{role:item.role,status:item.status}}if(endpoint==='public')return{leaders:clone(localDB.leaders),announcements:clone(localDB.announcements.slice(0,12)),gallery:clone(localDB.gallery.slice(0,18)),settings:clone(localDB.settings)};if(endpoint==='admin/login'&&method==='POST'){if(String(body.id).trim()!==ADMIN_ID||String(body.password)!==ADMIN_PASSWORD)throw new Error('Incorrect admin ID or password.');sessionStorage.setItem(ADMIN_KEY,'1');return{ok:true}}if(endpoint==='admin/logout'){sessionStorage.removeItem(ADMIN_KEY);return{ok:true}}requireLocalAdmin();if(endpoint==='admin/summary')return{counts:{members:localDB.members.length,pendingMembers:localDB.members.filter(x=>x.status==='pending').length,approvedMembers:localDB.members.filter(x=>x.status==='approved').length,leaders:localDB.leaders.length,announcements:localDB.announcements.length,gallery:localDB.gallery.length},settings:clone(localDB.settings)};if(endpoint.startsWith('admin/members')){const u=new URL('http://x/'+endpoint),o=Object.fromEntries(u.searchParams);return localPage('members',o.page||1,Number(o.pageSize)||50,o.search||'',o.status||'all')}if(endpoint==='admin/leaders')return{rows:clone(localDB.leaders)};if(endpoint.startsWith('admin/announcements')){const u=new URL('http://x/'+endpoint),o=Object.fromEntries(u.searchParams);return localPage('announcements',o.page||1,Number(o.pageSize)||30,o.search||'','')}if(endpoint.startsWith('admin/gallery')){const u=new URL('http://x/'+endpoint),o=Object.fromEntries(u.searchParams);return localPage('gallery',o.page||1,Number(o.pageSize)||24,o.search||'','')}if(endpoint==='admin/settings'&&method==='GET')return{settings:clone(localDB.settings)};if(endpoint==='admin/settings'&&method==='PUT'){localDB.settings={...localDB.settings,...body};saveLocal();return{settings:clone(localDB.settings)}}
if(endpoint==='admin/reset'&&method==='POST'){localDB=clone(defaultData);saveLocal();return{ok:true}};
const statusMatch=endpoint.match(/^members\/(\d+)\/status$/);if(statusMatch&&method==='PATCH'){const item=localDB.members.find(x=>Number(x.id)===Number(statusMatch[1]));const next=String(body.status||'').toLowerCase();if(!item)throw new Error('Member not found.');if(!['pending','approved','rejected'].includes(next))throw new Error('Invalid membership status.');item.status=next;saveLocal();return{ok:true}}
const m=endpoint.match(/^(members|leaders|announcements|gallery)\/(\d+)(?:\/photo)?$/);if(m){const[type,id]=m;const item=(localDB[type]||[]).find(x=>Number(x.id)===Number(id));if(!item)throw new Error('Item not found.');if(endpoint.endsWith('/photo')&&method==='PATCH'){Object.assign(item,{photo:String(body.photo||''),photoZoom:clamp(body.photoZoom,1,1,3),photoX:clamp(body.photoX,50,0,100),photoY:clamp(body.photoY,50,0,100)});saveLocal();return{ok:true}}if(method==='PUT'){if(type==='members')Object.assign(item,{name:String(body.name||item.name).trim(),phone:String(body.phone||item.phone).trim(),email:String(body.email||item.email).trim(),reason:String(body.reason||item.reason).trim()});if(type==='leaders')Object.assign(item,{name:String(body.name||item.name).trim(),role:String(body.role||item.role).trim()});if(type==='announcements')Object.assign(item,{title:String(body.title||item.title).trim(),body:String(body.body||item.body).trim()});if(type==='gallery'){item.title=String(body.title||item.title).trim();if(body.photo!==undefined)item.photo=String(body.photo||'')}saveLocal();return{ok:true}}if(method==='DELETE'){localDB[type]=localDB[type].filter(x=>Number(x.id)!==Number(id));saveLocal();return{ok:true}}}
if(endpoint==='members'&&method==='POST'){const name=String(body.name||'').trim(),phone=String(body.phone||'').trim(),email=String(body.email||'').trim(),reason=String(body.reason||'').trim();if(!name||!phone||!email||!reason)throw new Error('Please complete every membership field.');const memberNo=localDB.members.reduce((m,x)=>Math.max(m,Number(x.memberNo)||0),0)+1;const member={id:Date.now(),memberNo,name,phone,email,reason,role:`YYC-${String(memberNo).padStart(3,'0')}-${name.toUpperCase().replace(/[^A-Z]/g,'').slice(0,12)||'MEMBER'}`,status:'pending',createdAt:new Date().toISOString(),photo:String(body.photo||''),photoZoom:clamp(body.photoZoom,1,1,3),photoX:clamp(body.photoX,50,0,100),photoY:clamp(body.photoY,50,0,100)};localDB.members.unshift(member);saveLocal();return{member:clone(member)}}
if(/^leaders|announcements|gallery$/.test(endpoint)&&method==='POST'){const type=endpoint;if(type==='leaders')localDB.leaders.push({id:Date.now(),name:String(body.name||'').trim(),role:String(body.role||'').trim(),photo:String(body.photo||''),photoZoom:1,photoX:50,photoY:50});if(type==='announcements')localDB.announcements.unshift({id:Date.now(),date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),title:String(body.title||'').trim(),body:String(body.body||'').trim()});if(type==='gallery')localDB.gallery.push({id:Date.now(),position:localDB.gallery.length,title:String(body.title||'').trim(),photo:String(body.photo||'')});saveLocal();return{ok:true}}throw new Error('Unsupported operation.')}
async function api(endpoint,opts={}){if(STATIC_MODE)return staticApi(endpoint,opts);const response=await fetch('/api/'+endpoint,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const ct=response.headers.get('content-type')||'';if(!ct.includes('application/json'))throw new Error('YYC server returned an invalid response. Start the site with Start YYC.bat.');const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed.');return result}

function imageTag(src,alt='',lazy=true){return `<img ${lazy?'loading="lazy" decoding="async"':''} src="${escapeHtml(src||'./assets/lion-symbol.webp')}" alt="${escapeHtml(alt)}" onerror="this.onerror=null;this.src='./assets/lion-symbol.webp'">`}
function renderPublic(){
  $('#leaderGrid').innerHTML=publicData.leaders.map(x=>`<article class="leader-card"><div class="leader-avatar photo-frame">${x.photo?`<img loading="lazy" decoding="async" src="${escapeHtml(x.photo)}" alt="${escapeHtml(x.name)}" style="object-position:${clamp(x.photoX,50,0,100)}% ${clamp(x.photoY,50,0,100)}%;transform:scale(${clamp(x.photoZoom,1,1,3)})" onerror="this.onerror=null;this.src='./assets/lion-symbol.webp'">`:`<span>${escapeHtml(initials(x.name))}</span>`}</div><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.role)}</p></article>`).join('');
  $('#announcementList').innerHTML=publicData.announcements.map(x=>`<article class="announcement"><time>${escapeHtml(x.date)}</time><div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.body)}</p></div><b class="arr">→</b></article>`).join('');
  const positions=['55% 60%','20% 55%','72% 35%','45% 20%'];$('#galleryGrid').innerHTML=publicData.gallery.map((x,i)=>`<div class="gallery-item"><img loading="lazy" decoding="async" src="./assets/yyc-hero.webp" alt="${escapeHtml(x.title)}" style="object-position:${positions[i%positions.length]}"><span>${escapeHtml(x.title)}</span></div>`).join('');
  const s=publicData.settings||defaultSettings;document.querySelectorAll('[data-setting]').forEach(el=>{const k=el.dataset.setting;if(s[k]!=null)el.textContent=s[k]});
}
async function refreshPublic(){publicData=await api('public');renderPublic()}

function adminShell(tab){const views=['overview','members','leaders','announcements','gallery','settings'];document.querySelectorAll('.admin-view').forEach(v=>{const on=v.dataset.adminView===tab;v.hidden=!on;v.classList.toggle('is-active',on)});document.querySelectorAll('.admin-side-btn').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab)});}
function adminBusy(message='Loading…'){const v=document.querySelector(`.admin-view[data-admin-view="${adminState.tab}"]`);if(v&&!v.querySelector('.admin-loading')){const d=document.createElement('div');d.className='admin-loading';d.textContent=message;v.prepend(d)}}
function clearBusy(){document.querySelectorAll('.admin-loading').forEach(x=>x.remove())}
function renderSummary(){const c=adminState.summary?.counts||{};for(const[k,id]of Object.entries({members:'statMembers',pendingMembers:'statPending',approvedMembers:'statApproved',leaders:'statLeaders',announcements:'statAnnouncements',gallery:'statGallery'})){const el=$('#'+id);if(el)el.textContent=Number(c[k]||0).toLocaleString('en-IN')}$('#adminDbNote').textContent=`SQLite database · ${Number(c.members||0).toLocaleString('en-IN')} members · designed for 10,000+ records`}
function memberRow(x){const status=String(x.status||'pending');const contextual=status==='approved'?'<button data-action=\"status\" data-status=\"pending\" data-id=\"'+x.id+'\">↺ Pending</button>':status==='rejected'?'<button data-action=\"status\" data-status=\"pending\" data-id=\"'+x.id+'\">↺ Restore</button>':'';return `<div class=\"admin-record member-record\"><div class=\"admin-record-main\"><div class=\"admin-thumb\">${x.photo?`<img loading=\"lazy\" src=\"${escapeHtml(x.photo)}\" alt=\"${escapeHtml(x.name)}\" onerror=\"this.onerror=null;this.src='./assets/lion-symbol.webp'\">`:`<span>${escapeHtml(initials(x.name))}</span>`}</div><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.role)} · ${escapeHtml(x.phone)}</small><small>${escapeHtml(x.email)}</small></div></div><span class=\"status-pill ${escapeHtml(status)}\">${escapeHtml(status)}</span><div class=\"record-actions\"><button class=\"primary-action\" data-action=\"edit-member\" data-id=\"${x.id}\">✎ Edit</button><button class=\"success-action\" data-action=\"status\" data-status=\"approved\" data-id=\"${x.id}\">✓ Approve</button><button class=\"danger-soft\" data-action=\"status\" data-status=\"rejected\" data-id=\"${x.id}\">✕ Deny</button><button data-action=\"photo\" data-type=\"members\" data-id=\"${x.id}\">Photo</button>${contextual}<button class=\"danger\" data-action=\"delete\" data-type=\"members\" data-id=\"${x.id}\">Delete</button></div></div>`}
function leaderRow(x){return `<div class="admin-record leader-record"><div class="admin-record-main"><div class="admin-thumb">${x.photo?`<img loading="lazy" src="${escapeHtml(x.photo)}" alt="${escapeHtml(x.name)}" onerror="this.onerror=null;this.src='./assets/lion-symbol.webp'">`:`<span>${escapeHtml(initials(x.name))}</span>`}</div><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.role)}</small></div></div><div class="record-actions"><button data-action="edit-leader" data-id="${x.id}">Edit</button><button data-action="photo" data-type="leaders" data-id="${x.id}">Photo</button><button class="danger" data-action="delete" data-type="leaders" data-id="${x.id}">Delete</button></div></div>`}
function updateRow(x){return `<div class="admin-record update-record"><div><span class="record-date">${escapeHtml(x.date)}</span><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.body)}</p></div><div class="record-actions"><button data-action="edit-update" data-id="${x.id}">Edit</button><button class="danger" data-action="delete" data-type="announcements" data-id="${x.id}">Delete</button></div></div>`}
function galleryRow(x){return `<article class="admin-media-card"><img loading="lazy" decoding="async" src="${escapeHtml(x.photo||'./assets/yyc-hero.webp')}" alt="${escapeHtml(x.title)}" onerror="this.onerror=null;this.src='./assets/yyc-hero.webp'"><div><strong>${escapeHtml(x.title)}</strong><div class="record-actions"><button data-action="edit-gallery" data-id="${x.id}">Edit</button><button class="danger" data-action="delete" data-type="gallery" data-id="${x.id}">Delete</button></div></div></article>`}
function pagination(target,prefix){return `<div class="admin-pagination"><button ${target.page<=1?'disabled':''} data-action="page" data-target="${prefix}" data-page="${target.page-1}">← Prev</button><span>Page ${target.page} of ${target.pages} · ${Number(target.total).toLocaleString('en-IN')}</span><button ${target.page>=target.pages?'disabled':''} data-action="page" data-target="${prefix}" data-page="${target.page+1}">Next →</button></div>`}
function renderMembers(){const x=adminState.members;$('#memberCountLabel').textContent=`${Number(x.total).toLocaleString('en-IN')} records`;$('#membersTable').innerHTML=x.rows.length?x.rows.map(memberRow).join(''):`<div class="admin-empty">No members found.</div>`;$('#membersPager').innerHTML=pagination(x,'members')}
function renderLeaders(){const x=adminState.leaders;$('#leaderCountLabel').textContent=`${x.rows.length} leaders`;$('#leadersTable').innerHTML=x.rows.length?x.rows.map(leaderRow).join(''):`<div class="admin-empty">No leaders yet.</div>`}
function renderUpdates(){const x=adminState.announcements;$('#updateCountLabel').textContent=`${Number(x.total).toLocaleString('en-IN')} updates`;$('#updatesTable').innerHTML=x.rows.length?x.rows.map(updateRow).join(''):`<div class="admin-empty">No updates found.</div>`;$('#updatesPager').innerHTML=pagination(x,'announcements')}
function renderGallery(){const x=adminState.gallery;$('#galleryCountLabel').textContent=`${Number(x.total).toLocaleString('en-IN')} images`;$('#galleryTable').innerHTML=x.rows.length?x.rows.map(galleryRow).join(''):`<div class="admin-empty">No gallery images yet.</div>`;$('#galleryPager').innerHTML=pagination(x,'gallery')}
function applySettingsForm(){const s=adminState.settings;document.querySelectorAll('#settingsForm [name]').forEach(i=>{if(s[i.name]!=null)i.value=s[i.name]})}
async function loadAdminTab(tab){adminState.tab=tab;adminShell(tab);clearBusy();adminBusy();try{if(tab==='overview'){adminState.summary=await api('admin/summary');renderSummary()}if(tab==='members'){const x=adminState.members;const q=new URLSearchParams({page:x.page,pageSize:50,search:x.search,status:x.status==='all'?'':x.status});adminState.members=await api('admin/members?'+q)}if(tab==='leaders')adminState.leaders=await api('admin/leaders');if(tab==='announcements'){const x=adminState.announcements;const q=new URLSearchParams({page:x.page,pageSize:30,search:x.search});adminState.announcements=await api('admin/announcements?'+q)}if(tab==='gallery'){const x=adminState.gallery;const q=new URLSearchParams({page:x.page,pageSize:24,search:x.search});adminState.gallery=await api('admin/gallery?'+q)}if(tab==='settings'){adminState.settings=(await api('admin/settings')).settings;applySettingsForm();}if(tab==='members')renderMembers();if(tab==='leaders')renderLeaders();if(tab==='announcements')renderUpdates();if(tab==='gallery')renderGallery()}catch(e){const v=document.querySelector(`.admin-view[data-admin-view="${tab}"]`);if(v)v.insertAdjacentHTML('beforeend',`<div class="admin-error">${escapeHtml(e.message)}</div>`)}finally{clearBusy()}}
async function saveSettings(){const payload=Object.fromEntries(new FormData($('#settingsForm')));const btn=$('#saveSettingsBtn');btn.disabled=true;try{adminState.settings=(await api('admin/settings',{method:'PUT',body:JSON.stringify(payload)})).settings;await refreshPublic();btn.textContent='Saved ✓';setTimeout(()=>btn.textContent='Save site settings',1200)}catch(e){alert(e.message)}finally{btn.disabled=false}}
async function refreshCurrent(){await loadAdminTab(adminState.tab)}
async function addRecord(form){const type=form.dataset.add,raw=Object.fromEntries(new FormData(form)),btn=form.querySelector('button[type=submit]');btn.disabled=true;try{if(raw.photoFile){raw.photo=await fileToDataUrl(raw.photoFile);delete raw.photoFile}else delete raw.photoFile;await api(type,{method:'POST',body:JSON.stringify(raw)});form.reset();if(type==='leaders'||type==='announcements'||type==='gallery')await loadAdminTab(type==='announcements'?'announcements':type);else {adminState.members.page=1;await loadAdminTab('members')}adminState.summary=null}catch(e){alert(e.message)}finally{btn.disabled=false}}
async function recordDelete(type,id){if(!confirm('Delete this item permanently?'))return;try{await api(`${type}/${id}`,{method:'DELETE'});await refreshCurrent()}catch(e){alert(e.message)}}
async function recordStatus(id,status){try{await api(`members/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await loadAdminTab('members')}catch(e){alert(e.message)}}
async function editRecord(type,id){let item;if(type==='members')item=adminState.members.rows.find(x=>Number(x.id)===Number(id));if(type==='leaders')item=adminState.leaders.rows.find(x=>Number(x.id)===Number(id));if(type==='announcements')item=adminState.announcements.rows.find(x=>Number(x.id)===Number(id));if(type==='gallery')item=adminState.gallery.rows.find(x=>Number(x.id)===Number(id));if(!item)return;const modalId= type==='members'?'editMemberModal':type==='leaders'?'editLeaderModal':type==='announcements'?'editUpdateModal':'editGalleryModal';const m=$('#'+modalId);m.dataset.type=type;m.dataset.id=id;const fields={members:['name','phone','email','reason','status'],leaders:['name','role'],announcements:['title','body'],gallery:['title']}[type];fields.forEach(k=>{const el=m.querySelector(`[name="${k}"]`);if(el)el.value=item[k]??''});modal('#'+modalId,true)}
async function submitEdit(m){const type=m.dataset.type,id=m.dataset.id,payload=Object.fromEntries(new FormData(m.querySelector('form')));try{const nextStatus=type==='members'?payload.status:null;if(type==='members')delete payload.status;await api(`${type}/${id}`,{method:'PUT',body:JSON.stringify(payload)});if(type==='members'&&nextStatus)await api(`members/${id}/status`,{method:'PATCH',body:JSON.stringify({status:nextStatus})});modal('#'+m.id,false);await loadAdminTab(adminState.tab)}catch(e){alert(e.message)}}
function openPhotoEditor(type,id){const item=(type==='members'?adminState.members.rows:adminState.leaders.rows).find(x=>Number(x.id)===Number(id));if(!item)return;$('#photoEditor').dataset.type=type;$('#photoEditor').dataset.id=id;$('#photoFileInput').value='';$('#photoZoom').value=item.photoZoom||1;$('#photoX').value=item.photoX??50;$('#photoY').value=item.photoY??50;$('#photoZoomValue').textContent=`${Number($('#photoZoom').value).toFixed(1)}×`;$('#photoPreviewImg').src=item.photo||'./assets/lion-symbol.webp';updatePhotoPreview();modal('#photoEditor',true)}
function updatePhotoPreview(){const img=$('#photoPreviewImg');img.style.objectPosition=`${$('#photoX').value}% ${$('#photoY').value}%`;img.style.transform=`scale(${$('#photoZoom').value})`;$('#photoZoomValue').textContent=`${Number($('#photoZoom').value).toFixed(1)}×`}
async function savePhoto(){const type=$('#photoEditor').dataset.type,id=$('#photoEditor').dataset.id,src=$('#photoPreviewImg').src,p={photo:src.startsWith('data:image/')?src:'',photoZoom:Number($('#photoZoom').value),photoX:Number($('#photoX').value),photoY:Number($('#photoY').value)};try{await api(`${type}/${id}/photo`,{method:'PATCH',body:JSON.stringify(p)});modal('#photoEditor',false);await loadAdminTab(type)}catch(e){alert(e.message)}}
function modal(id,show){$(id).classList.toggle('hidden',!show)}
function fileToDataUrl(file){if(!file)return Promise.resolve('');if(!file.type.startsWith('image/'))return Promise.reject(new Error('Please choose an image file.'));return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,sc=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*sc));c.height=Math.max(1,Math.round(im.height*sc));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};im.onerror=()=>reject(new Error('Could not decode image.'));im.src=r.result};r.onerror=()=>reject(new Error('Could not read image.'));r.readAsDataURL(file)})}


// Public membership application: every new application starts as pending and the member is told so immediately.
const joinForm=$('#joinForm');
if(joinForm){
  const joinFile=$('#joinPhotoFile');
  const bindJoinPhoto=async()=>{try{const f=joinFile?.files?.[0]; if(!f) return; const data=await fileToDataUrl(f); $('#joinPhotoData').value=data; $('#joinPhotoPreview').src=data;}catch(e){alert(e.message)}};
  joinFile?.addEventListener('change',bindJoinPhoto);
  ['joinPhotoZoom','joinPhotoX','joinPhotoY'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{const z=Number($('#joinPhotoZoom').value||1); const x=Number($('#joinPhotoX').value||50); const y=Number($('#joinPhotoY').value||50); $('#joinPhotoZoomValue').textContent=`${z.toFixed(1)}×`; $('#joinPhotoZoomData').value=z; $('#joinPhotoXData').value=x; $('#joinPhotoYData').value=y; $('#joinPhotoPreview').style.objectPosition=`${x}% ${y}%`; $('#joinPhotoPreview').style.transform=`scale(${z})`}));
  $('#joinPhotoReset')?.addEventListener('click',()=>{joinFile.value='';$('#joinPhotoData').value='';$('#joinPhotoZoom').value=1;$('#joinPhotoX').value=50;$('#joinPhotoY').value=50;$('#joinPhotoZoomData').value=1;$('#joinPhotoXData').value=50;$('#joinPhotoYData').value=50;$('#joinPhotoZoomValue').textContent='1.0×';$('#joinPhotoPreview').src='./assets/lion-symbol.webp';$('#joinPhotoPreview').style.objectPosition='50% 50%';$('#joinPhotoPreview').style.transform='scale(1)'});
  joinForm.addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const payload=Object.fromEntries(new FormData(joinForm));delete payload.photoFile;const result=await api('members',{method:'POST',body:JSON.stringify(payload)});const m=result.member||result;$('#memberName').textContent=m.name||payload.name;$('#roleId').textContent=m.role||'Pending';modal('#successModal',true);joinForm.reset();$('#joinPhotoData').value='';$('#joinPhotoPreview').src='./assets/lion-symbol.webp';['joinPhotoZoom','joinPhotoX','joinPhotoY'].forEach((id,i)=>$('#'+id).value=[1,50,50][i]);$('#joinPhotoZoomValue').textContent='1.0×';}catch(err){alert(err.message)}finally{btn.disabled=false}});
}
const statusCheckForm=$('#statusCheckForm');
if(statusCheckForm){statusCheckForm.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#statusCheckMessage'),btn=e.submitter;btn.disabled=true;msg.textContent='Checking…';msg.className='form-message status-checking';try{const form=new FormData(statusCheckForm);const q=new URLSearchParams({role:String(form.get('role')||''),phone:String(form.get('phone')||'')});const r=await api('member-status?'+q);const labels={pending:'PENDING — waiting for admin approval',approved:'APPROVED — welcome to Yuvakesari Youth Club',rejected:'DENIED — please contact the club admin'};msg.textContent=`${r.role}: ${labels[r.status]||r.status}`;msg.className=`form-message status-result ${r.status}`}catch(err){msg.textContent=err.message;msg.className='form-message status-result rejected'}finally{btn.disabled=false}})}

// Navigation and admin events
const navRoot=$('.nav'),navMenu=$('#navMenu');if(navRoot&&navMenu){navMenu.onclick=()=>{const open=navRoot.classList.toggle('mobile-open');navMenu.setAttribute('aria-expanded',open?'true':'false')};document.querySelectorAll('.nav nav a').forEach(a=>a.onclick=()=>{navRoot.classList.remove('mobile-open');navMenu.setAttribute('aria-expanded','false')})}
$('#adminBtn').onclick=()=>{$('#adminLoginMessage').textContent='';modal('#adminLoginModal',true)};
document.querySelectorAll('.close,.close-action').forEach(b=>b.onclick=()=>document.querySelectorAll('.modal').forEach(m=>modal('#'+m.id,false)));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)modal('#'+m.id,false)}));
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api('admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});modal('#adminLoginModal',false);modal('#adminModal',true);await loadAdminTab('overview')}catch(err){$('#adminLoginMessage').textContent=err.message}finally{btn.disabled=false}};
$('#logoutBtn').onclick=async()=>{await api('admin/logout',{method:'POST'});modal('#adminModal',false);await refreshPublic()};

document.querySelectorAll('.admin-side-btn').forEach(b=>b.onclick=()=>loadAdminTab(b.dataset.tab));
document.querySelectorAll('form[data-add]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();addRecord(f)}));
$('#settingsForm').onsubmit=e=>{e.preventDefault();saveSettings()};
$('#resetBtn').onclick=async()=>{if(!confirm('Reset demo data? This clears the current local database.'))return;try{await api('admin/reset',{method:'POST'});await refreshCurrent();await refreshPublic()}catch(e){alert(e.message)}};
let memberSearchTimer;$('#membersSearch').oninput=()=>{clearTimeout(memberSearchTimer);memberSearchTimer=setTimeout(()=>{adminState.members.search=$('#membersSearch').value;adminState.members.page=1;loadAdminTab('members')},220)};$('#memberStatusFilter').onchange=()=>{adminState.members.status=$('#memberStatusFilter').value;adminState.members.page=1;loadAdminTab('members')};
let updateSearchTimer,gallerySearchTimer;$('#updatesSearch').oninput=()=>{clearTimeout(updateSearchTimer);updateSearchTimer=setTimeout(()=>{adminState.announcements.search=$('#updatesSearch').value;adminState.announcements.page=1;loadAdminTab('announcements')},220)};$('#gallerySearch').oninput=()=>{clearTimeout(gallerySearchTimer);gallerySearchTimer=setTimeout(()=>{adminState.gallery.search=$('#gallerySearch').value;adminState.gallery.page=1;loadAdminTab('gallery')},220)};
$('#adminContent').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,type=b.dataset.type;if(a==='delete')return recordDelete(type,id);if(a==='status')return recordStatus(id,b.dataset.status);if(a==='photo')return openPhotoEditor(type,id);if(a==='edit-member')return editRecord('members',id);if(a==='edit-leader')return editRecord('leaders',id);if(a==='edit-update')return editRecord('announcements',id);if(a==='edit-gallery')return editRecord('gallery',id);if(a==='page'){if(b.dataset.target==='members')adminState.members.page=Number(b.dataset.page);if(b.dataset.target==='announcements')adminState.announcements.page=Number(b.dataset.page);if(b.dataset.target==='gallery')adminState.gallery.page=Number(b.dataset.page);return loadAdminTab(b.dataset.target)}});
['editMemberModal','editLeaderModal','editUpdateModal','editGalleryModal'].forEach(id=>$('#'+id)?.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();submitEdit($('#'+id))}));
$('#photoFileInput').onchange=async e=>{try{const s=await fileToDataUrl(e.target.files[0]);if(s){$('#photoPreviewImg').src=s;updatePhotoPreview()}}catch(err){alert(err.message)}};['photoZoom','photoX','photoY'].forEach(id=>$('#'+id).oninput=updatePhotoPreview);$('#photoSaveBtn').onclick=savePhoto;

const stories={coast:['Between the green Western Ghats and the Arabian Sea, Tulu Nadu is a place where community, celebration, and courage move together.','Salt-air mornings, temple bells, and a deep sense of belonging.'],art:['Yakshagana brings myth, music, colour, and movement together in an all-night theatre tradition that continues to inspire new generations.','A living art form where every character arrives with presence and purpose.'],field:['Kambala celebrates the energy of the land—an iconic buffalo-racing festival set in the rich, water-filled fields of coastal Karnataka.','A reminder that heritage is not behind us; it moves with us.']};document.querySelectorAll('.story-tab').forEach(b=>b.onclick=()=>{const[s,n]=stories[b.dataset.story];$('.story-tab.active')?.classList.remove('active');b.classList.add('active');$('#tuluStoryText').textContent=s;$('#tuluStoryNote').textContent=n});
const observer=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){en.target.classList.add('is-visible');observer.unobserve(en.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));

// V19: native <picture> handles exact mobile/desktop hero selection; no JS image swap needed.
document.querySelectorAll('img').forEach(image=>imageFallback(image));
// Keep non-critical sections cheap to render. The hero is the only eager visual asset.
document.querySelectorAll('.section, .join-section, footer').forEach(el=>el.style.contentVisibility='auto');
refreshPublic().catch(e=>console.error(e));
